version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "cchacin"
    default_labels:
      - "dependabot"
    target_branch: "master"

    allowed_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "all"