version: "3.7"
services:
  portainer:
    image: portainer/portainer:1.22.0
    container_name: portainer
    hostname: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/portainer_password:/tmp/portainer_password
    ports:
      - 9000:9000
      - 8000:8000
    command: --admin-password='$$2y$$05$$U6g.5sn3AAJRShJD2Yahh.QW.K9B2YdSj4.SuGZRlpo14W1My08E2'
    # username:admin password: portainer

  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.4.0
    container_name: filebeat
    hostname: filebeat
    depends_on:
      - elasticsearch
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /tmp/logs:/tmp/logs
    user: root

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.4.0
    container_name: kibana
    hostname: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  zipkin:
    image: openzipkin/zipkin:2.17.1
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus:v2.13.0
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana:6.4.1
    container_name: grafana
    hostname: grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  ${rootArtifactId}:
    image: ${groupId}/${rootArtifactId}:${version}
    container_name: ${rootArtifactId}
    hostname: ${rootArtifactId}
    depends_on:
      - kibana
      - zipkin
      - grafana
    ports:
      - 9080:9080
      - 9443:9443
    volumes:
      - /tmp/logs:/tmp/logs
volumes:
  prometheus_data: {}
  grafana_data: {}