version: "3.7"
services:
  portainer:
    image: portainer/portainer:1.23.2
    container_name: ${rootArtifactId}-portainer
    hostname: ${rootArtifactId}-portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/portainer_password:/tmp/portainer_password
    ports:
      - 9000:9000
      - 8000:8000
    command: --admin-password='$$2y$$05$$U6g.5sn3AAJRShJD2Yahh.QW.K9B2YdSj4.SuGZRlpo14W1My08E2'
    # username:admin password: portainer

  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.6.1
    container_name: ${rootArtifactId}-filebeat
    hostname: ${rootArtifactId}-filebeat
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /tmp/logs:/tmp/logs
    user: root

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.1
    container_name: ${rootArtifactId}-elasticsearch
    hostname: ${rootArtifactId}-elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.6.1
    container_name: ${rootArtifactId}-kibana
    hostname: ${rootArtifactId}-kibana
    ports:
      - 5601:5601

  zipkin:
    image: openzipkin/zipkin-slim:2.20.2
    container_name: ${rootArtifactId}-zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411

  prometheus:
    image: prom/prometheus:v2.16.0
    container_name: ${rootArtifactId}-prometheus
    hostname: ${rootArtifactId}-prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana:6.7.1
    container_name: ${rootArtifactId}-grafana
    hostname: ${rootArtifactId}-grafana
    user: "104"
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  postgres:
    image: postgres:12.2-alpine
    container_name: ${rootArtifactId}-postgres
    hostname: ${rootArtifactId}-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer:4.7.6-standalone
    container_name: ${rootArtifactId}-adminer
    hostname: ${rootArtifactId}-adminer
    restart: always
    ports:
      - 8080:8080

  ${rootArtifactId}:
    image: ${rootArtifactId}:${version}
    container_name: ${rootArtifactId}
    hostname: ${rootArtifactId}
    environment:
      - WLP_LOGGING_CONSOLE_LOGLEVEL=info
      - WLP_LOGGING_CONSOLE_SOURCE=message,trace,accessLog,ffdc
      - WLP_LOGGING_CONSOLE_FORMAT=json
      - WLP_LOGGING_MESSAGE_FORMAT=json
      - WLP_LOGGING_MESSAGE_SOURCE=message
      - LOG_DIR=/tmp/logs
    depends_on:
      - ${rootArtifactId}-filebeat
      - ${rootArtifactId}-zipkin
      - ${rootArtifactId}-prometheus
      - ${rootArtifactId}-postgres
    ports:
      - 9080:9080
      - 9443:9443
    volumes:
      - /tmp/logs:/tmp/logs
volumes:
  prometheus_data: {}
  grafana_data: {}
